apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/data-contract-api/namespace.yaml
  - apps/data-contract-api/deployment.yaml
  - apps/data-contract-api/service.yaml
  - apps/data-contract-api/networkpolicy.yaml
